#!/bin/expect -f

set timeout -1
set username [lindex $argv 0]

spawn docker run -v {{ openvpn_dir }}:/etc/openvpn --log-driver=none --rm -it docker.fabric8.ru/devops/openvpn-ldap:{{ docker_tag }} easyrsa build-client-full $username nopass
match_max 100000
expect "*Enter pass phrase for /etc/openvpn/pki/private/ca.key:"
send -- "{{ ca_password }}\r"
expect eof