#!/bin/bash
rm -f {{ openvpn_dir }}/client_configs/$1.ovpn
docker run -v {{ openvpn_dir }}:/etc/openvpn --log-driver=none --rm docker.fabric8.ru/devops/openvpn-ldap:{{ docker_tag }} ovpn_git /etc/openvpn